// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5VvYhUvxHcwK-yseGvI4fOI6VMLhpG0',
    appId: '1:4332200019:web:93ed96625328145b78e6a6',
    messagingSenderId: '4332200019',
    projectId: 'manger-app-3aa3b',
    authDomain: 'manger-app-3aa3b.firebaseapp.com',
    storageBucket: 'manger-app-3aa3b.firebasestorage.app',
    measurementId: 'G-WPRYJWWLT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwL3Qt3-fcnWicU5kaTGlS2q0JmKynFN8',
    appId: '1:4332200019:android:44fcba0fc75de6ce78e6a6',
    messagingSenderId: '4332200019',
    projectId: 'manger-app-3aa3b',
    storageBucket: 'manger-app-3aa3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjsIkAH8TYVkGDxvdlYjpssBCd1OOjjhc',
    appId: '1:4332200019:ios:4a69902167af2b5078e6a6',
    messagingSenderId: '4332200019',
    projectId: 'manger-app-3aa3b',
    storageBucket: 'manger-app-3aa3b.firebasestorage.app',
    iosBundleId: 'com.example.mangerPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjsIkAH8TYVkGDxvdlYjpssBCd1OOjjhc',
    appId: '1:4332200019:ios:4a69902167af2b5078e6a6',
    messagingSenderId: '4332200019',
    projectId: 'manger-app-3aa3b',
    storageBucket: 'manger-app-3aa3b.firebasestorage.app',
    iosBundleId: 'com.example.mangerPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO5VvYhUvxHcwK-yseGvI4fOI6VMLhpG0',
    appId: '1:4332200019:web:40d978542dd60d1878e6a6',
    messagingSenderId: '4332200019',
    projectId: 'manger-app-3aa3b',
    authDomain: 'manger-app-3aa3b.firebaseapp.com',
    storageBucket: 'manger-app-3aa3b.firebasestorage.app',
    measurementId: 'G-PW7NQ1DCZR',
  );
}
